### Kiara's Tutorial

Practicing with `XARRAY`.

In [7]:
#importing numpy package
import numpy as np

In [2]:
import pandas as pd

In [3]:
import xarray as xr

In [8]:
data = np.random.rand(4,3)

In [9]:
locs = ["IA","IL", "IN"]

In [10]:
times = pd.date_range("2000-01-01", periods=4)

In [7]:
foo = xr.DataArray(data, coords=[times,locs], dims=["time", "space"])

In [8]:
foo

<xarray.DataArray (time: 4, space: 3)>
array([[0.48693108, 0.43237184, 0.64998427],
       [0.99163812, 0.0085329 , 0.49534334],
       [0.98874709, 0.46717225, 0.08261529],
       [0.6271525 , 0.05486592, 0.96656044]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [9]:
xr.DataArray(data)

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.48693108, 0.43237184, 0.64998427],
       [0.99163812, 0.0085329 , 0.49534334],
       [0.98874709, 0.46717225, 0.08261529],
       [0.6271525 , 0.05486592, 0.96656044]])
Dimensions without coordinates: dim_0, dim_1

In [10]:
xr.DataArray(data, coords=[("time", times), ("space", locs)])

<xarray.DataArray (time: 4, space: 3)>
array([[0.48693108, 0.43237184, 0.64998427],
       [0.99163812, 0.0085329 , 0.49534334],
       [0.98874709, 0.46717225, 0.08261529],
       [0.6271525 , 0.05486592, 0.96656044]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [11]:
df = pd.DataFrame({"x": [0, 1], "y":[2, 3]}, index=["a", "b"])

In [12]:
df.index.name = "abc"

In [13]:
df.columns.name = "xyz"

In [14]:
df

xyz  x  y
abc      
a    0  2
b    1  3

In [15]:
xr.DataArray(df)

<xarray.DataArray (abc: 2, xyz: 2)>
array([[0, 2],
       [1, 3]])
Coordinates:
  * abc      (abc) object 'a' 'b'
  * xyz      (xyz) object 'x' 'y'

In [16]:
foo.values

array([[0.48693108, 0.43237184, 0.64998427],
       [0.99163812, 0.0085329 , 0.49534334],
       [0.98874709, 0.46717225, 0.08261529],
       [0.6271525 , 0.05486592, 0.96656044]])

In [17]:
foo.dims

('time', 'space')

In [18]:
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [19]:
foo.attrs

{}

In [20]:
print(foo.name)

None


In [21]:
foo.values = 1.0 * foo.values

In [22]:
foo.name = "foo"

In [23]:
foo

<xarray.DataArray 'foo' (time: 4, space: 3)>
array([[0.48693108, 0.43237184, 0.64998427],
       [0.99163812, 0.0085329 , 0.49534334],
       [0.98874709, 0.46717225, 0.08261529],
       [0.6271525 , 0.05486592, 0.96656044]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [24]:
foo.rename("bar")

<xarray.DataArray 'bar' (time: 4, space: 3)>
array([[0.48693108, 0.43237184, 0.64998427],
       [0.99163812, 0.0085329 , 0.49534334],
       [0.98874709, 0.46717225, 0.08261529],
       [0.6271525 , 0.05486592, 0.96656044]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [25]:
foo.coords["time"]

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [26]:
foo["time"]

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [27]:
foo["ranking"] = ("space", [1, 2, 3])

In [28]:
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    ranking  (space) int64 1 2 3

In [29]:
del foo["ranking"]

In [30]:
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [31]:
temp = 15 + 8 * np.random.randn(2, 2, 3)

In [32]:
precip = 10 * np.random.rand(2, 2, 3)

In [33]:
lon = [[-99.83, -99.32], [-99.79, -99.23]]

In [34]:
lat = [[42.25, 42.21], [42.63, 42.59]]

In [35]:
ds = xr.Dataset(
....:{
....:   "temperature": (["x", "y", "time"], temp),
....:   "precipitation": (["x", "y", "time"], precip),
....: },
....: coords={
....:     "lon": (["x", "y"], lon),
....:     "lat": (["x","y"], lat),
....:     "time": pd.date_range("2014-09-06", periods=3),
....:     "reference_time": pd.Timestamp("2014-09-05"),
....: },
....: )
....:

In [36]:
ds

<xarray.Dataset>
Dimensions:         (time: 3, x: 2, y: 2)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 31.44 9.521 26.65 ... 9.695 14.27 15.83
    precipitation   (x, y, time) float64 4.563 6.515 4.761 ... 3.803 5.302 8.145

In [37]:
xr.Dataset({"bar": foo})

<xarray.Dataset>
Dimensions:  (space: 3, time: 4)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Data variables:
    bar      (time, space) float64 0.4869 0.4324 0.65 ... 0.6272 0.05487 0.9666

In [38]:
xr.Dataset({"bar": foo.to_pandas()})

<xarray.Dataset>
Dimensions:  (space: 3, time: 4)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) object 'IA' 'IL' 'IN'
Data variables:
    bar      (time, space) float64 0.4869 0.4324 0.65 ... 0.6272 0.05487 0.9666

In [39]:
"temperature" in ds

True

In [40]:
ds["temperature"]

<xarray.DataArray 'temperature' (x: 2, y: 2, time: 3)>
array([[[31.44135005,  9.52061628, 26.65095069],
        [ 8.71442028,  6.36245659, 28.47535574]],

       [[ 6.56449757, 15.92260463,  8.88603174],
        [ 9.69477011, 14.26689607, 15.83429751]]])
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y

In [41]:
ds.data_vars

Data variables:
    temperature    (x, y, time) float64 31.44 9.521 26.65 ... 9.695 14.27 15.83
    precipitation  (x, y, time) float64 4.563 6.515 4.761 ... 3.803 5.302 8.145

In [42]:
ds.coords

Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05

In [43]:
ds.attrs

{}

In [44]:
ds.attrs["title"] = "example attribute"

In [45]:
ds

<xarray.Dataset>
Dimensions:         (time: 3, x: 2, y: 2)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 31.44 9.521 26.65 ... 9.695 14.27 15.83
    precipitation   (x, y, time) float64 4.563 6.515 4.761 ... 3.803 5.302 8.145
Attributes:
    title:    example attribute

In [46]:
ds.temperature

<xarray.DataArray 'temperature' (x: 2, y: 2, time: 3)>
array([[[31.44135005,  9.52061628, 26.65095069],
        [ 8.71442028,  6.36245659, 28.47535574]],

       [[ 6.56449757, 15.92260463,  8.88603174],
        [ 9.69477011, 14.26689607, 15.83429751]]])
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y

In [47]:
ds = xr.Dataset()

In [48]:
ds["temperature"] = (("x", "y", "time"), temp)

In [49]:
ds["temperature_double"] = (("x", "y", "time"), temp * 2)

In [50]:
ds["precipitation"] = (("x", "y", "time"), precip)

In [51]:
ds.coords["lat"] = (("x", "y"), lat)

In [53]:
ds.coords["lon"] = (("x", "y"), lon)

In [54]:
ds.coords["time"] = pd.date_range("2014-09-06", periods=3)

In [55]:
ds.coords["reference_time"] = pd.Timestamp("2014-09-05")

In [56]:
ds[["temperature"]]

<xarray.Dataset>
Dimensions:         (time: 3, x: 2, y: 2)
Coordinates:
    lat             (x, y) float64 42.25 42.21 42.63 42.59
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 31.44 9.521 26.65 ... 9.695 14.27 15.83

In [57]:
ds[["temperature", "temperature_double"]]

<xarray.Dataset>
Dimensions:             (time: 3, x: 2, y: 2)
Coordinates:
    lat                 (x, y) float64 42.25 42.21 42.63 42.59
    lon                 (x, y) float64 -99.83 -99.32 -99.79 -99.23
  * time                (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time      datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature         (x, y, time) float64 31.44 9.521 26.65 ... 14.27 15.83
    temperature_double  (x, y, time) float64 62.88 19.04 53.3 ... 28.53 31.67

In [58]:
ds.drop_vars("temperature")

<xarray.Dataset>
Dimensions:             (time: 3, x: 2, y: 2)
Coordinates:
    lat                 (x, y) float64 42.25 42.21 42.63 42.59
    lon                 (x, y) float64 -99.83 -99.32 -99.79 -99.23
  * time                (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time      datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature_double  (x, y, time) float64 62.88 19.04 53.3 ... 28.53 31.67
    precipitation       (x, y, time) float64 4.563 6.515 4.761 ... 5.302 8.145